name: main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    env:
      POETRY_VIRTUALENVS_IN_PROJECT: true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install poetry==1.1.7
      - name: cache venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install
      - name: static code analysis
        run: |
          poetry run black --check ipfs_video_kodi test
      - run: poetry run pytest
      - name: build package
        run: |
          make clean
          make package
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: build/plugin_video_ipfs.zip
          retention-days: 3
          if-no-files-found: error
